# Generated by Django 3.1.7 on 2021-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.PositiveIntegerField(default=9999999999),
        ),
    ]
